

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: sales_crm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Miyako2020
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:Miyako2020@postgres:5432/sales_crm
      - JWT_SECRET=your-super-secret-jwt-key-here-change-this-in-production
      - PORT=3000
      - NODE_ENV=development
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./public:/app/public
      - ./routes:/app/routes
      - ./prisma:/app/prisma

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 